# Generated by Django 6.0.2 on 2026-02-14 07:37

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draweritem',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
